name: Sanity Check

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: build-package
    env:
      PLASMO_PUBLIC_SENTRY_DSN: ${{ vars.PLASMO_PUBLIC_SENTRY_DSN }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Build the extension
        run: pnpm build --source-maps
      - name: Package extension artifact
        run: pnpm package
      - name: Transform to "Google Workspace Zoom Default"
        run: pnpm transform-ext
      - name: Build the extension
        run: pnpm build --source-maps
      - name: Package extension artifact
        run: pnpm package
