name: Sanity Check

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # environment:
    #   name: build-package
    # env:
    #   PLASMO_PUBLIC_SENTRY_DSN: ${{ vars.PLASMO_PUBLIC_SENTRY_DSN }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build the extension
        run: |
          pnpm build --source-maps --target=chrome-mv3
          pnpm build --source-maps --target=edge-mv3
          pnpm build --source-maps --target=firefox-mv2
      - name: Package extension artifact
        run: |
          pnpm package --target=chrome-mv3
          pnpm package --target=edge-mv3
          pnpm package --target=firefox-mv2
      - name: Transform to "Google Workspace Zoom Default"
        run: pnpm transform-ext
      - name: Build the extension
        run: |
          pnpm build --source-maps --target=chrome-mv3
          pnpm build --source-maps --target=edge-mv3
          pnpm build --source-maps --target=firefox-mv2
      - name: Package extension artifact
        run: |
          pnpm package --target=chrome-mv3
          pnpm package --target=edge-mv3
          pnpm package --target=firefox-mv2
