#This is exactly the same as the default one minus the "Transform to "Google Workspace Zoom Default"" and Sentry steps
name: "(extended) Submit to Web Store"
on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: build-package-extended
    env:
      PLASMO_PUBLIC_SENTRY_DSN: ${{ vars.PLASMO_PUBLIC_SENTRY_DSN }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: 9.10.0
          run_install: true
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Build the extension
        run: pnpm build --source-maps
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          environment: production
          sourcemaps: "./build/chrome-mv3-prod"
          url_prefix: "chrome-extension://mdgikencgfhineaememjagpkiclbdkka"
          ignore_empty: true
          version: ${{ steps.package-version.outputs.current-version }}
      - name: Remove sourcemaps from bundle
        run: rm ./build/chrome-mv3-prod/*.map
      - name: Package extension artifact
        run: pnpm package
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS_EXTENDED }}
          artifact: build/chrome-mv3-prod.zip
