name: "(default) Submit to Web Store"
on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: build-package
    env:
      PLASMO_PUBLIC_SENTRY_DSN: ${{ vars.PLASMO_PUBLIC_SENTRY_DSN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ vars.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Transform to "Google Workspace Zoom Default"
        run: pnpm transform-ext
      - name: Build the extension
        run: |
          pnpm build --source-maps --target=chrome-mv3
          pnpm build --no-minify --no-hoist --source-maps --zip --target=firefox-mv2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Create Sentry release (Chrome Extension)
        uses: getsentry/action-release@v1
        with:
          environment: production
          sourcemaps: "./build/chrome-mv3-prod"
          url_prefix: "chrome-extension://nflkcdlimipkgbacnfnhfecjgmojhklo"
          ignore_empty: true
          ignore_missing: true
          version: ${{ steps.package-version.outputs.current-version }}
      - name: Create Sentry release (Firefox Add-on)
        uses: getsentry/action-release@v1
        with:
          environment: production
          sourcemaps: "./build/firefox-mv3-prod"
          # url_prefix: "chrome-extension://nflkcdlimipkgbacnfnhfecjgmojhklo"
          ignore_empty: true
          ignore_missing: true
          version: ${{ steps.package-version.outputs.current-version }}
      # NOTE: This has to be after Sentry Release is created above...
      - name: Remove sourcemaps from bundle
        run: |
          rm ./build/chrome-mv3-prod/*.map
          rm ./build/firefox-mv2-prod/*.map
      - name: Package extension artifact
        run: |
          pnpm package --target=chrome-mv3
          pnpm package --target=firefox-mv2
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          chrome-file: build/chrome-mv3-prod.zip
          firefox-file: build/firefox-mv2-prod.zip
